# docker-compose.yml
version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: dashboard_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: lead_dashboard
    ports:
      - "5432:5432"
    volumes:
      - dashboard_db_data:/var/lib/postgresql/data

volumes:
  dashboard_db_data: